---
- name: Install Docker
  hosts: test-server  # Replace with the hostname or IP address of your test server
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Install Docker Prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker Repository Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes
